# Generated by Django 5.0.2 on 2025-12-02 19:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("notebooks", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ShareLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "token",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "access_level",
                    models.CharField(
                        choices=[
                            ("READ", "Read Only"),
                            ("COMMENT", "Can Comment"),
                            ("EDIT", "Can Edit"),
                        ],
                        max_length=10,
                    ),
                ),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("password_hash", models.CharField(blank=True, max_length=128)),
                ("max_uses", models.IntegerField(blank=True, null=True)),
                ("use_count", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("last_accessed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_share_links",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "notebook",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="share_links",
                        to="notebooks.notebook",
                    ),
                ),
            ],
            options={
                "db_table": "share_links",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ShareLinkAccess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("accessed_by_email", models.EmailField(blank=True, max_length=254)),
                ("ip_address", models.GenericIPAddressField(null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("accessed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "share_link",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accesses",
                        to="sharing.sharelink",
                    ),
                ),
            ],
            options={
                "db_table": "share_link_accesses",
                "ordering": ["-accessed_at"],
            },
        ),
        migrations.AddIndex(
            model_name="sharelink",
            index=models.Index(fields=["token"], name="share_links_token_5e7a57_idx"),
        ),
        migrations.AddIndex(
            model_name="sharelink",
            index=models.Index(
                fields=["notebook", "is_active"], name="share_links_noteboo_672eb7_idx"
            ),
        ),
    ]
