# Generated by Django 5.0.2 on 2025-12-03 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sharing", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sharelink",
            name="access_level",
            field=models.CharField(
                choices=[("READ", "Read Only"), ("EDIT", "Can Edit")], max_length=10
            ),
        ),
    ]
