# Generated by Django 5.0.2 on 2025-12-04 13:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("notebooks", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NotebookConflict",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("server_version", models.IntegerField()),
                ("client_version", models.IntegerField()),
                ("base_content", models.TextField()),
                ("your_content", models.TextField()),
                ("their_content", models.TextField()),
                ("resolved_content", models.TextField(blank=True)),
                ("conflict_blocks", models.JSONField(default=list)),
                (
                    "resolution_strategy",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("AUTO_MERGED", "Auto-merged"),
                            ("YOURS", "Kept your changes"),
                            ("THEIRS", "Kept their changes"),
                            ("MANUAL", "Manually merged"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("conflict_data", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "notebook",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conflicts",
                        to="notebooks.notebook",
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolved_conflicts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notebook_conflicts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "notebook_conflicts",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["notebook", "resolution_strategy"],
                        name="notebook_co_noteboo_20995a_idx",
                    ),
                    models.Index(
                        fields=["user", "created_at"],
                        name="notebook_co_user_id_67dcd9_idx",
                    ),
                ],
            },
        ),
    ]
