# Generated by Django 5.0.2 on 2025-12-03 20:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("workspaces", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ActivityLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("Created workspace", "Created workspace"),
                            ("Updated workspace", "Updated workspace"),
                            ("Added member", "Added member"),
                            ("Removed member", "Removed member"),
                            ("Changed member role", "Changed member role"),
                            ("Created notebook", "Created notebook"),
                            ("Updated notebook", "Updated notebook"),
                            ("Deleted notebook", "Deleted notebook"),
                            ("Restored notebook", "Restored notebook"),
                            ("Created label", "Created label"),
                            ("Added label to notebook", "Added label to notebook"),
                            (
                                "Removed label from notebook",
                                "Removed label from notebook",
                            ),
                            ("Created share link", "Created share link"),
                            ("Revoked share link", "Revoked share link"),
                        ],
                        max_length=30,
                    ),
                ),
                ("target_type", models.CharField(max_length=50)),
                ("target_id", models.IntegerField(null=True)),
                ("target_title", models.CharField(max_length=300)),
                ("metadata", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "db_table": "activity_logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["workspace", "-created_at"],
                        name="activity_lo_workspa_27d3b0_idx",
                    ),
                    models.Index(
                        fields=["actor", "-created_at"],
                        name="activity_lo_actor_i_929704_idx",
                    ),
                ],
            },
        ),
    ]
